### ISSUE TITLE
Bug in the CptLoader::load() - up to 100 records in the tail of the file may not be saved in the database 

### ISSUE THREAD

**Issue by predatoralpha** [onc-healthit/code-validator-api#93]
CptLoader::load() - local variable _pendingCount_ newer changes, as a result the final insert to the database not performed.
`            if (pendingCount > 0) {
                insertCode(insertQueryBuilder.toString(), connection);
            }
`

PS: can someone assign this to me?

**Comment by Plow74** [comment]
Hi there. We will create a ticket and investigate this. Thank you for bringing it to our attention!

**Comment by AndriiPr** [comment]
PR with a solution to the problem :
https://github.com/onc-healthit/code-validator-api/pull/94

**Comment by drbgfc** [comment]
This is merged, closing
